{% set version = '0.1-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-alluvial
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/alluvial_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/alluvial/alluvial_{{ version }}.tar.gz
  sha256: 77b6dc4651b33b03aaaf1e09a35f9c3536e5fddac2eda34f5a34e0ae33cf2e0d

build:
  merge_build_host: True  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('alluvial')"           # [not win]
    - "\"%R%\" -e \"library('alluvial')\""  # [win]

about:
  home: https://github.com/mbojan/alluvial
  license: MIT
  summary: Creating alluvial diagrams (also known as parallel sets plots) for multivariate and
    time series-like data.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: alluvial
# Type: Package
# Title: Alluvial Diagrams
# Version: 0.1-2
# Date: 2016-09-09
# Authors@R: c( person("Michal", "Bojanowski", role=c("aut", "cre"), email="michal2992@gmail.com"), person("Robin", "Edwards", role="aut", email="robin.edwards@ucl.ac.uk") )
# Description: Creating alluvial diagrams (also known as parallel sets plots) for multivariate and time series-like data.
# URL: https://github.com/mbojan/alluvial
# BugReports: https://github.com/mbojan/alluvial/issues
# Suggests: devtools, testthat, reshape2, knitr, rmarkdown, dplyr
# License: MIT + file LICENSE
# LazyLoad: yes
# LazyData: yes
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-09-09 09:58:05 UTC; mbojan
# Author: Michal Bojanowski [aut, cre], Robin Edwards [aut]
# Maintainer: Michal Bojanowski <michal2992@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-09-09 13:08:51
