travis:
  secure:
    BINSTAR_TOKEN: TUms2GK3Lenh7oYUMOujKtyKbR7CuKGCl4iCUNhYIciEtMdkXXVKWiJ/qO0+ZKxp/wYitSIho3iVIyqimBqmQWN33WXN2Zw4+FBuwK9tlnoF/cqflPUcL9G6RaBX+/wx6vaWOCwfaImvuBeRijFrQk67M8oD2HVWbcnTqGpJXJWi0NpT/IhrRZ9C3snwsfukiHZglggMAsoqi9hx0XXntEf0YYmUGaUOkWTR2t2e6JEpIiOhL+d6Mx7dMkyn7ZykI3ikAdx9PAydJ4JJuAMdVrwc0poAPHJNQFl/3/mfgG9K3QTB+9+Xq3nAxd91s59PGJT9weXnunvNtOtMi2mpANqbUMwggmqGp3Beir1iVcea2PS32G6KVPXYlFkYSfue6xtiLc7Y1zHxTYO5tSsFF5ldyvKp3AmuEJ/nXfcfiXtE+GePTp2n5stjCvX2W5ZGf9PFIzyyUSSDMGkFj1ua8s6wYZ4b1V6Ip+X1OjjbHk1jXJye6Dzq7DIxCH/Jn9us9lkoWqi4aMR4Htx/eh7B0JuvOUZ3S/pMCwm5eXlChb7Rg+5IXLEyCjAQg3ktWplRhXnJqw2zASuMLgBWhXUS4MkzmwUpM1OHBizI3VNcCLn/rpSCztNHpUC7QxZ0rxgw66+l2k8PMXzxM9884Cioh6EdeiUQ9V7/oUhNpzo3rXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
