appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AbmDvpRdwV5uWqupJpti10RdO4ZQEnwdPF0vTm9TXTn8QdnvM3ct8W9Y+Fj0vzuJeL5+RyBPD+l4/wPg+KKwpAknFYdb/9XUk1eFGT+q4vOJOtJ5jttjRLbXxjQxJjoIGGAGFt27B0b0BBNXJ/zykoGIRZ/osaLaknOG4bezFyZl5JzakbOLQTlrOPwKCs30TeGT6mdU1gM+2WpXL61IQsMznWwRnbgCl059ykxJurbm1uzcD2UE6tZ9wpg5J6GKZ2A7XJz5b9kvGPt+Vvk13/9HXfu1ZwwV19YgcNZXZe3QW6mABSwKmNcULLsXVFHtiLd98Uxd4O0mn7tO5UjJJJ1ESTrM9Bpny0rns4Zp1vm2LXGpSW1lwPnk+Ji20FZulQa2PlRTKgfXquL+FkDOM+Qdqq9WN5dgz3Sev2snrS8fnhJdDv52U2LnLNT6BcDxs/4+wzX9oZEQogD3u9rqVw+5kbHVuqtlpS1tWCNTf/r/c2sXzCXgZXoMvCd7XYEIGw3VUPZDFe6CFfrojeBhCK32V4KxmNWWqY8BKKA30FbGU6f5GuZ1ilFo1tfkl/XzYPVyvrZ8M1AJ3xd6biUb+4pX5kCdETFr3RF5cdJTTdCe2WZQEgBb7QDAmh5Gx19g8WBV6XU/KFudTgrWe9jFlEzBG+czv3UU5gfVJZI2RnQ=
conda_forge_output_validation: true
