travis:
  secure:
    BINSTAR_TOKEN: h906gNNjhNKEesRAxCaoqK01HgQvhY7KXXFxcDN45T8tMsHWuiimq6kUV9NbcJR5sw1wdTJzc6EwvXl4M9S37HCFnzEzKACO9y0251fDEvB7dhq94SFlKKiLpbCrLMTTCpV539dvT4Nz9+WAhJbRrqD1Kuxxb4esQWQ3e68Av0GF6xeJek+liTjFcAownZtwsZWyOaEraGQ5+kKMcbMBFFQdrBuvoMSGC7dQJWOEsL5+Q1hCNI4whe7IanHAb0rRPDju3+8joUIE/mbGDT5gEpq2w2pcAj7O4/fJTSU67SDjaNhD8VLgB7bXU1LGukX4WppRYaTMt3+AejgUkYGdPKWWPIFfeuWkEKhA2pYkZzb1EquFbsZjwNaKc9gVev04OREH8PU2jIsW41X2jmNQ3tJPiD1tR0+2Vo6H5yHTSTRQHdiV+uJnNzQgG8HYc/hMaZo+9GmeA+QTTw6e8xF5Lg1MU1rsBRbXmvG735qHUaFo+etn3LZHKjweZdw4sx6G5NLu4fx2DsWuUDBYC8tc7mHCQOja76VcrfU/WvXMcBhYhWVyRkF2hyPZx530PKN6BmjLO+VyEZqfhzz86m+ixt6oUB98ZzwIMBcExI4C1+yVWBKUFfeOlj394z6s2nXhZ0MUPpLLsP7meSJksD5XkSWy5riazLmLBfvS1xEe6As=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
